### ISSUE TITLE
Control panel on the left under construction

### ISSUE THREAD

**Issue by Yida-Lin** [labstreaminglayer/App-SigVisualizer#14]
Currently the control panel on the left with checkboxes are not functional, yet. Ideally it should control which stream/channels are being streamed, and when checkbox is toggled, the changes should be reflected immediately.

**Comment by cboulay** [comment]
It's not ready yet but my branch also interacts with the control panel on the left:
https://github.com/labstreaminglayer/App-SigVisualizer/tree/multi_stream

I fear we'll have some big conflicts. If you aren't too far along in fixing this change, maybe you want to branch off my branch, or test my branch then merge it to master if it doesn't break anything on your end.

There are a couple things that are incomplete, as far as I know. First, even though streams with unknown rates are actually plotted now, they don't properly make use of the available timestamps so we end up with 20 seconds of data. Second, switching between streams doesn't immediately reset the display to show all channels, only as many channels as were present in the previous stream. It fixes itself once it makes a full sweep. Third, I'm not sure what's going on with the sample rate when switching from one stream to another. I'll need to test with a signal generator.

**Comment by Yida-Lin** [comment]
Great! Thanks @cboulay . I will take a look

**Comment by Yida-Lin** [comment]
It works great! I didn't know you were working on this before. Would you mind rebasing your branch onto the current master and create a PR please? That would be wonderful. Thanks
